services:
  - type: web
    name: hack-store-bot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: hack_store_enterprise
      - key: PAY_SVC_HOST
        value: 0.0.0.0
